### PR TITLE
v1.0.0 documentation

### PR DESCRIPTION
**Pull request by ntwb**
In preparation for a v1.0.0 release with Stylelint v1.0.1 and PostCSS v5.0.4

### CODE REVIEW

**Comment by jeddy3** [comment]
I'm wondering whether we need this. Isn't this config already compatible with postcss 4 and 5? i.e. if I'm not missing something, won't this config work with both stylelint `0.8.0` and `1.0.1`?

**Comment by ntwb** [comment]
Hadn't quite thought of it that way but I think you're correct and this wouldn't be needed.

(After https://github.com/stylelint/stylelint/issues/363 the other day I'm all in _4.x or 5.x, don't mix 'em, you'll have a bad day_ mode)

Rather than bumping to `1.0.0`, a `0.3.0` release would suffice?

**Comment by jeddy3** [comment]
> (After stylelint/stylelint#363 the other day I'm all in 4.x or 5.x, don't mix 'em, you'll have a bad day mode)

Ha, I know exactly what you mean. I start on a new project last week and I had to dig out postcss 4 compatible plugins for everything. Fortunately, now that stylelint is postcss 5 compatible, I was able to update all the plugins to the latest versions over the weekend :)

> Rather than bumping to 1.0.0, a 0.3.0 release would suffice?

I'm wondering whether a bump is needed at all. The deps bump has no effect on the consumers of the config (who the github and npm releases are meant for). I think adding the deps bump to master is fine (as it for us - the config maintainers) and we'll get out another release when the config itself changes.

What do you think?

**Comment by jeddy3** [comment]
P.S. I'm pretty new this release stuff, so what I'm suggesting might be totally wrong :)

**Comment by ntwb** [comment]
> I'm wondering whether a bump is needed at all. The deps bump has no effect on the consumers of the config (who the github and npm releases are meant for). I think adding the deps bump to master is fine (as it for us - the config maintainers) and we'll get out another release when the config itself changes.

If we _don't_ bump it then the version installed via `npm install stylelint-config-wordpress` only includes Stlyelint 0.8.0, as Stylelint 1.0.0 is a major semver bump and as such is not installed, thus we miss out on the new and improved accurate line number/column reporting :smile: 

Note: NPM packages are stored on NPM's own CDN servers, the packages are not sourced directly from the GitHub repo

P.S. Likewise, I'm maybe even newer on this release stuff :smirk:

**Comment by jeddy3** [comment]
Now you're confusing me :) 

I had to double check how all this works, but `stylelint` and `postcss` won't be installed when `npm install stylelint-config-wordpress` is used as they are _dev_ dependencies (used only for testing changes to the config). The only files in the `node_modules/stylelint-config-wordpress` are :1234:  

* `CHANGELOG.md`
* `LICENSE`
* `README.md`
* `index.js`
* `package.json`

> Note: NPM packages are stored on NPM's own CDN servers, the packages are not sourced directly from the GitHub repo

Yep. I meant [these github releases](https://github.com/stylelint/stylelint-config-wordpress/releases).

So, there shouldn't be any conflicts with stylelint versions when using either these github releases or the ones stored on npm. I think... :)

**Comment by ntwb** [comment]
Right, 100% with you now, did the same and yeah we're good, I think :smirk:

**Comment by jeddy3** [comment]
Glad we're on the same page now :)

**Pull request closed without merging**
