### PR TITLE
No quotes for URLs

### PR DESCRIPTION
**Pull request by GaryJones**
See example at https://make.wordpress.org/core/handbook/best-practices/coding-standards/css/#values.

### CODE REVIEW

**Comment by jeddy3** [comment]
Thanks for the PR!

@ntwb Looks good to me. Do you want me to merge this in a do a release?

**Comment by ntwb** [comment]
Thanks Gary :+1: 

Now  to go publish an update, give us a bit of time for this one ;)

**Comment by ntwb** [comment]
Yay... `0.2.0` released :smiley: 

https://github.com/stylelint/stylelint-config-wordpress/releases
https://www.npmjs.com/package/stylelint-config-wordpress

Everything looks good from my viewpoint, but hey, what would I know, if you see an issue with the release let me know :smirk:

**Comment by GaryJones** [comment]
No extra warnings came up when switching from 0.1.0 to 0.2.0, so all looking good from a quick test.

**Comment by ntwb** [comment]
Thanks :+1:

**Comment by jeddy3** [comment]
@ntwb The release looks good to me :)

**Comment by ntwb** [comment]
Woot :dancers:

**Pull request merged**
