### PR TITLE
Add release npm script

### PR DESCRIPTION
**Pull request by ntwb**

### CODE REVIEW

**Comment by ntwb** [comment]
@jeddy3 Based off of https://github.com/stylelint/stylelint/pull/618

I think this should just work providing `GITHUB_TOKEN` environment variable is correctly defined etc

**Comment by ntwb** [comment]
Theoretically now after https://github.com/stylelint/stylelint-config-wordpress/commit/524e3e3b64353103ec8b6a449b8544c519198617 running `npm run release` should release version `1.1.0` of `stylelint-config-wordpress` I think :smirk:

**Comment by jeddy3** [comment]
> Theoretically now after 524e3e3 running npm run release should release version 1.1.0 of stylelint-config-wordpress I think

Fingers crossed hey :)

**Comment by ntwb** [comment]
Looks good:
• GitHub Tag :+1: 
• GitHub Release :+1: 
• 1.1.0 published on npmjs.com :+1:

**Comment by jeddy3** [comment]
Nice!

**Comment by MoOx** [comment]
:)

**Comment by ntwb** [comment]
Thanks @MoOx :)

**Pull request merged**
